### ISSUE TITLE
Add API to get assignment group by date

### ISSUE THREAD

**Issue by TopsonArcana** [GarnBarn/garnbarn-backend#17]
## Is your feature request related to a problem? Please describe.
I was using the existing API to get assignment data by date to display on the frontend. In the process, I felt that grouping data on the front end might not be a good idea for several reasons.
1. There's a lot of processing than doing it in the backend.
2. When data is called the assignment on the same date, it's possible the data is on a different page leading to a new problem.

## Describe the solution you'd like
Create an API to get the assignment data ordered by date and grouped by date.

**Comment by sirateek** [comment]
Does anyone still work on this? If not, I'll close as a won't fix.

**Comment by sirateek** [comment]
As no one answered my question. I'll close this issue as a won't fix issue
