### ISSUE TITLE
[BUG]: fromPresent dueDate must focus on date.

### ISSUE THREAD

**Issue by abounk** [GarnBarn/garnbarn-backend#19]
## Describe the bug
The fromPresent should return the assignment that have dueDate >= today (Focus manly on Day not date-time)

## Expected behavior

Ex:
Current time - 12 Sep. 12:00
Assignment 1 Due date - 12 Sep. 11:00
Assignment 2 Due date - 13 Sep. 8:00

The assignment that should be returned to the user is both of them (Assignment 1 is included because it is still on 12 Sep.)

**Comment by sirateek** [comment]
This has been implemented in #22
