### ISSUE TITLE
POST returns 201 response

### ISSUE THREAD

**Issue by jbrucker** [GarnBarn/garnbarn-backend#34]
In your API for the backend, when a client uses POST to create
a new resource, it is common to return 201 (Created) instead of 200 (OK).
Sending a 200 reply is OK, too.  Just that 201 is more descriptive.
Also common to return a Location header containing the URL of 
the new resource.

For example, if someone sends
```
POST /api/v1/assignment/
Content-type: application/json

(assignment data)
```

and your app created a new assignment with id 234 then it would respond:
```
HTTP/1.1  201 Created
Host: garnbarn.web.app
Location: /api/v1/assignment/234
Content-type: application/json

(assignment data in body -- this is optional)
```

The Location header can be useful to the client using your API.

**Comment by abounk** [comment]
I see your point to make it more descriptive. I'll fix this in our iteration 4, thank you for your advice 🙏.

**Comment by SoSorryTT** [comment]
This issue was done in #43.
